server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:client-configs/

# === Git private repo config storage - not needed but it was cool
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: git repo
#          ignoreLocalSshSettings: true
#          privateKey: |
#                        -----BEGIN RSA PRIVATE KEY-----
#                        -----END RSA PRIVATE KEY-----