# TODO Includes refresh endpoint, maybe it can be moved to config server
# TODO or changed to bus refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    org:
#      springframework: debug
